### ISSUE TITLE
User and Tablature data (from contexts) are briefly undefined when a page is refreshed

### ISSUE THREAD

**Issue by dcollis92** [RyanSUP/riffin-v2#53]
### **Tablature State**

In the process of creating the **ProtectedEditRoute**, Ryan noticed that the user's Tablature was appearing as null/undefined. This in turn, has the ProcRoute continuously renavigating to `/new`, since the tab will always be undefined regardless of correct user or not.

Once this information is able to be passed over via the **TablatureProvider**, the ProcRoute functionality should hopefully work.

**Comment by RyanSUP** [comment]
Thanks for bringing this issue to light Dave.

**The issue is that the application as a whole doesn't handle an undefined user state** - it just keeps going until it crashes and burns. The TablatureProvider having undefined data is a symptom of the user being undefined because TablatureProvider derives all its data from user. To address this we need to build functionality that makes the app wait until user is defined before continuing, and in some cases (like the protected route) handle the event where there may be no user.
